"""
core/providers/pleias

LLM provider for Pleias RAG models loaded directly via llama-cpp-python.

Pleias models use a custom prompt format with special tokens that cannot
be expressed as a plain QA_PROMPT template. The format is:

    <|query_start|>{query}<|query_end|>
    <|source_start|><|source_id_start|>1<|source_id_end|>{text}<|source_end|>
    ...
    <|source_analysis_start|>

The model generates from <|source_analysis_start|> onward and stops at "#END#".
The final answer is extracted from between <|answer_start|> and <|answer_end|>
tags in the generated output.

rag_engine detects uses_source_list = True and calls generate()/stream() with
retrieved source chunks directly, bypassing LlamaIndex's response synthesizer.

Embeddings reuse the nomic-embed-text GGUF via LlamaCppEmbedding, the same
approach as LlamaCppProvider.
"""

from typing import Generator

from llama_cpp import Llama

from core.providers.base import BaseProvider
from core.providers.llamacpp import LlamaCppEmbedding, LlamaCppLLM
from utils.logger import setup_logger

logger = setup_logger()

# Generation parameters from official Pleias documentation
_TEMPERATURE = 0.0
_TOP_P = 0.95
_REPEAT_PENALTY = 1.0
_STOP_TOKENS = ["#END#"]
_MAX_TOKENS = 1024


def _build_prompt(query: str, sources: list) -> str:
    """
    Build the Pleias prompt string from a query and source list.

    Each source is numbered from 1. Source text is taken from the "text"
    key in each source dict. The prompt ends with <|source_analysis_start|>
    so the model generates from that token onward.

    Args:
        query (str): The user's query
        sources (list): Retrieved chunks as
            [{"text": "...", "metadata": {"source": "filename"}}]

    Returns:
        str: Fully formatted Pleias prompt
    """
    logger.info(f"_build_prompt | Query: '{query[:200]}' | Sources: {len(sources)}")
    parts = [f"<|query_start|>{query}<|query_end|>\n"]
    for i, source in enumerate(sources, start=1):
        text = source.get("text", "")
        logger.info(f"_build_prompt | Source {i}: '{text[:200]}'")
        parts.append(
            f"<|source_start|><|source_id_start|>{i}<|source_id_end|>"
            f"{text}<|source_end|>\n"
        )
    parts.append("<|source_analysis_start|>")
    return "".join(parts)


def _extract_answer(raw: str) -> str:
    """
    Extract the final answer from the model's raw generation output.

    Looks for text between <|answer_start|> and <|answer_end|>. If neither
    tag is present, returns the full raw output stripped of whitespace so
    partial or unexpected generations are still usable.

    Args:
        raw (str): Raw text generated by the model after <|source_analysis_start|>

    Returns:
        str: Extracted answer text
    """
    start_tag = "<|answer_start|>"
    end_tag = "<|answer_end|>"

    start = raw.find(start_tag)
    end = raw.find(end_tag)

    if start != -1 and end != -1 and end > start:
        return raw[start + len(start_tag):end].strip()

    if start != -1:
        return raw[start + len(start_tag):].strip()

    return raw.strip()


class PleiasProvider(BaseProvider):
    """
    LLM provider for Pleias RAG models using llama-cpp-python directly.

    Builds the Pleias special-token prompt format, runs generation with
    the parameters from official Pleias documentation, and extracts the
    clean answer from between <|answer_start|> and <|answer_end|> tags.

    uses_source_list = True signals to rag_engine that this provider must be
    called with sources rather than through LlamaIndex's response synthesizer.
    """

    uses_source_list: bool = True

    def __init__(self, config: dict):
        """
        Initialize the Pleias provider from config.

        Loads the Pleias GGUF from pleias_model_path and the embedding model
        from embed_model_path.

        Args:
            config (dict): App config dict from config.yaml
        """
        pleias_model_path = config.get(
            "pleias_model_path", "./models/Pleias-RAG-1B-Q4_K_M.gguf"
        )
        embed_model_path = config.get(
            "embed_model_path", "./models/nomic-embed-text-v1.5.Q8_0.gguf"
        )
        n_gpu_layers = config.get("n_gpu_layers", -1)
        n_ctx = config.get("n_ctx", 4096)
        n_threads = config.get("n_threads", None)

        logger.info(f"Loading Pleias model | Path: {pleias_model_path} | GPU layers: {n_gpu_layers}")
        self._model = Llama(
            model_path=pleias_model_path,
            n_gpu_layers=n_gpu_layers,
            n_ctx=n_ctx,
            n_threads=n_threads,
            verbose=False,
        )
        logger.info("Pleias model loaded")

        logger.info(f"Loading embedding model | Path: {embed_model_path}")
        _embed_llm = Llama(
            model_path=embed_model_path,
            n_gpu_layers=n_gpu_layers,
            n_ctx=512,
            n_threads=n_threads,
            embedding=True,
            verbose=False,
        )
        self.embed_model = LlamaCppEmbedding(_embed_llm)
        self.llm = LlamaCppLLM(self._model)
        logger.info("Pleias provider ready | Generation and embedding models loaded")

    def generate(self, prompt: str, sources: list = None) -> str:
        """
        Generate a complete response using the Pleias prompt format.

        Builds the special-token prompt from the query and source chunks,
        calls the model with the official Pleias generation parameters, and
        extracts the clean answer from the output.

        Args:
            prompt (str): The user's query
            sources (list): Retrieved chunks formatted as
                [{"text": "...", "metadata": {"source": "filename"}}]

        Returns:
            str: Extracted answer from between <|answer_start|> and <|answer_end|>
        """
        if sources is None:
            sources = []

        full_prompt = _build_prompt(prompt, sources)
        logger.info(f"Pleias generate | Sources: {len(sources)}")

        response = self._model(
            full_prompt,
            max_tokens=_MAX_TOKENS,
            temperature=_TEMPERATURE,
            top_p=_TOP_P,
            repeat_penalty=_REPEAT_PENALTY,
            stop=_STOP_TOKENS,
            echo=False,
        )

        raw = response["choices"][0]["text"]
        answer = _extract_answer(raw)
        logger.info("Pleias generate complete")
        return answer

    def stream(self, prompt: str, sources: list = None) -> Generator[str, None, None]:
        """
        Stream a response token by token using the Pleias prompt format.

        Yields tokens from the model's stream. Accumulates the full output
        and yields only the extracted answer portion — tokens before
        <|answer_start|> are buffered silently and the answer content is
        yielded as it arrives. If <|answer_start|> is never seen, all tokens
        are yielded so the response is never silently empty.

        Stop token (#END#) is checked at the Python level across chunk
        boundaries because llama-cpp-python streaming mode does not reliably
        halt the generator for stop sequences that span multiple tokens.
        A rolling tail of len(stop) - 1 characters is kept from the previous
        chunk so that a stop token split across two successive raw tokens is
        still detected.

        Args:
            prompt (str): The user's query
            sources (list): Retrieved chunks formatted as
                [{"text": "...", "metadata": {"source": "filename"}}]

        Yields:
            str: Each token delta from the answer section of the response
        """
        if sources is None:
            sources = []

        full_prompt = _build_prompt(prompt, sources)
        logger.info(f"Pleias stream | Sources: {len(sources)}")

        start_tag = "<|answer_start|>"
        end_tag = "<|answer_end|>"

        buffer = ""
        answer_started = False

        # Rolling tail for cross-chunk stop token detection.
        # Holds the last len(stop_str) - 1 raw characters so that a stop
        # token split across two successive chunks is still caught at the
        # Python level, independent of whether llama-cpp-python enforces it.
        stop_str = _STOP_TOKENS[0]
        stop_len = len(stop_str)
        tail = ""

        for chunk in self._model(
            full_prompt,
            max_tokens=_MAX_TOKENS,
            temperature=_TEMPERATURE,
            top_p=_TOP_P,
            repeat_penalty=_REPEAT_PENALTY,
            stop=_STOP_TOKENS,
            echo=False,
            stream=True,
        ):
            raw = chunk["choices"][0]["text"]
            if not raw:
                continue

            # Prepend the tail from the previous chunk to detect a stop token
            # that was split across the chunk boundary.
            combined = tail + raw
            stop_pos = combined.find(stop_str)

            if stop_pos != -1:
                # Discard the stop token and everything after it.
                # Strip the tail prefix (already processed) to get the usable
                # portion of the current raw token only.
                token = combined[:stop_pos][len(tail):]
                stop_hit = True
            else:
                token = raw
                # Retain the last stop_len-1 chars for the next iteration.
                tail = combined[-(stop_len - 1):] if len(combined) >= stop_len else combined
                stop_hit = False

            if token:
                if answer_started:
                    # Stop yielding once the end tag begins to appear in the buffer
                    buffer += token
                    end_pos = buffer.find(end_tag)
                    if end_pos != -1:
                        # Yield everything up to the end tag and stop
                        remaining = buffer[:end_pos]
                        if remaining:
                            yield remaining
                        break
                    # Safe to yield up to len(buffer) - len(end_tag) + 1 chars
                    # to avoid splitting the end tag across two yields
                    safe = len(buffer) - len(end_tag) + 1
                    if safe > 0:
                        yield buffer[:safe]
                        buffer = buffer[safe:]
                else:
                    buffer += token
                    tag_pos = buffer.find(start_tag)
                    if tag_pos != -1:
                        answer_started = True
                        buffer = buffer[tag_pos + len(start_tag):]

            if stop_hit:
                break

        # If <|answer_start|> was never found, yield the full accumulated output
        # so a partial or unexpected generation is not silently dropped
        if not answer_started and buffer:
            yield buffer.strip()

        logger.info("Pleias stream complete")

    def get_embeddings(self, text: str) -> list:
        """
        Generate an embedding vector via the nomic-embed-text GGUF model.

        Args:
            text (str): The text to embed

        Returns:
            list: Embedding vector as a list of floats
        """
        return self.embed_model.get_text_embedding(text)
